modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="roughlyenoughitems"
    mandatory=true
    versionRange="[9.1.663,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ic2"
    mandatory=true
    versionRange="[1.19.2-2.0.9,)"
    ordering="AFTER"
    side="BOTH"
